# Generated by Django 4.2.3 on 2023-07-27 09:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter name of assignment",
                        max_length=40,
                        verbose_name="Assignment Name",
                    ),
                ),
                (
                    "grade_given",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="Enter grade given for the assignment",
                        max_digits=5,
                        verbose_name="Grade Given",
                    ),
                ),
                (
                    "total_grade",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="Enter the total grade for the assignment",
                        max_digits=5,
                        verbose_name="Total Grade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvaluationCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="Evaluation Criteria Name"
                    ),
                ),
                (
                    "weighting",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Weighting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("CS", "Computer Science"),
                            ("BA", "Business Administration"),
                            ("CE", "Computer Engineering"),
                            ("EE", "Electrical Engineering"),
                            ("MIS", "Management Information Systems"),
                            ("ME", "Mechanical Engineering"),
                        ],
                        default="BA",
                        max_length=30,
                        verbose_name="Major Name",
                    ),
                ),
                (
                    "total_credits",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(35),
                        ],
                        verbose_name="Total Credits",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Course ID",
                    ),
                ),
                (
                    "course_name",
                    models.CharField(max_length=200, verbose_name="Course Name"),
                ),
                (
                    "credits_worth",
                    models.IntegerField(
                        choices=[(1, "Full"), (0, "Half")],
                        default=1,
                        verbose_name="Credits Worth",
                    ),
                ),
                (
                    "letter_grade",
                    models.CharField(
                        max_length=2, null=True, verbose_name="Letter Grade"
                    ),
                ),
                (
                    "final_grade",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=5,
                        null=True,
                        verbose_name="Final Grade",
                    ),
                ),
                (
                    "course_gpa",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="Course GPA",
                    ),
                ),
                (
                    "associated_majors",
                    models.ManyToManyField(
                        to="courses.major", verbose_name="Associated Majors"
                    ),
                ),
                (
                    "evaluation_criteria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.evaluationcriteria",
                        verbose_name="Evaluation Criteria",
                    ),
                ),
                ("student", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
