# Generated by Django 4.2.3 on 2023-07-18 16:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("evaluation_criteria", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("CS", "Computer Science"),
                            ("BA", "Business Administration"),
                            ("CE", "Computer Engineering"),
                            ("EE", "Electrical Engineering"),
                            ("MIS", "Management Information Systems"),
                            ("ME", "Mechanical Engineering"),
                            ("GN", "General"),
                        ],
                        default="GN",
                        max_length=30,
                    ),
                ),
                (
                    "total_credits",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(34),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("course_name", models.CharField(max_length=40)),
                (
                    "credits_worth",
                    models.CharField(
                        choices=[(1, "Full"), (0, "Half")], default=1, max_length=4
                    ),
                ),
                (
                    "associated_majors",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.major",
                    ),
                ),
                (
                    "evaluation_criteria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="evaluation_criteria.evaluationcriteria",
                    ),
                ),
            ],
        ),
    ]
