# Generated by Django 4.2.3 on 2023-07-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter name of assignment", max_length=40
                    ),
                ),
                (
                    "grade_given",
                    models.IntegerField(
                        help_text="Enter grade given for the assignment"
                    ),
                ),
                (
                    "total_grade",
                    models.IntegerField(
                        help_text="Enter the total grade for the assignment"
                    ),
                ),
            ],
        ),
    ]
