# Generated by Django 4.2.3 on 2023-07-19 11:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("evaluation_criteria", "0002_alter_evaluationcriteria_name_and_more"),
        ("courses", "0002_assignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="grade_given",
            field=models.IntegerField(
                help_text="Enter grade given for the assignment",
                verbose_name="Grade Given",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="name",
            field=models.CharField(
                help_text="Enter name of assignment",
                max_length=40,
                verbose_name="Assignment Name",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="total_grade",
            field=models.IntegerField(
                help_text="Enter the total grade for the assignment",
                verbose_name="Total Grade",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="associated_majors",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.major",
                verbose_name="Associated Majors",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_id",
            field=models.CharField(
                max_length=8,
                primary_key=True,
                serialize=False,
                verbose_name="Course ID",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_name",
            field=models.CharField(max_length=40, verbose_name="Course Name"),
        ),
        migrations.AlterField(
            model_name="course",
            name="credits_worth",
            field=models.CharField(
                choices=[(1, "Full"), (0, "Half")],
                default=1,
                max_length=4,
                verbose_name="Credits Worth",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="evaluation_criteria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="evaluation_criteria.evaluationcriteria",
                verbose_name="Evaluation Criteria",
            ),
        ),
        migrations.AlterField(
            model_name="major",
            name="name",
            field=models.CharField(
                choices=[
                    ("CS", "Computer Science"),
                    ("BA", "Business Administration"),
                    ("CE", "Computer Engineering"),
                    ("EE", "Electrical Engineering"),
                    ("MIS", "Management Information Systems"),
                    ("ME", "Mechanical Engineering"),
                    ("GN", "General"),
                ],
                default="GN",
                max_length=30,
                verbose_name="Major Name",
            ),
        ),
        migrations.AlterField(
            model_name="major",
            name="total_credits",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(35),
                ],
                verbose_name="Total Credits",
            ),
        ),
    ]
