# Generated by Django 4.2.3 on 2023-07-19 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_alter_assignment_grade_given_alter_assignment_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="final_grade",
            field=models.DecimalField(
                decimal_places=5, max_digits=5, null=True, verbose_name="Final Grade"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="letter_grade",
            field=models.CharField(
                max_length=2, null=True, verbose_name="Letter Grade"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="grade_given",
            field=models.DecimalField(
                decimal_places=5,
                help_text="Enter grade given for the assignment",
                max_digits=5,
                verbose_name="Grade Given",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="total_grade",
            field=models.DecimalField(
                decimal_places=5,
                help_text="Enter the total grade for the assignment",
                max_digits=5,
                verbose_name="Total Grade",
            ),
        ),
        migrations.AlterField(
            model_name="major",
            name="total_credits",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(35),
                ],
                verbose_name="Total Credits",
            ),
        ),
    ]
