# Generated by Django 4.2.3 on 2023-07-19 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_course_final_grade_course_letter_grade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="major",
            name="total_credits",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(35),
                ],
                verbose_name="Total Credits",
            ),
        ),
    ]
