# Generated by Django 4.2.3 on 2023-07-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_alter_major_total_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_gpa",
            field=models.DecimalField(
                decimal_places=2, max_digits=3, null=True, verbose_name="Course GPA"
            ),
        ),
    ]
