# Generated by Django 4.2.3 on 2023-07-27 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_of_courses",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(6),
                            django.core.validators.MinValueValidator(4),
                        ],
                        verbose_name="Number of Courses",
                    ),
                ),
                (
                    "academic_term",
                    models.CharField(
                        choices=[
                            ("Y1S1", "Year 1 Semester 1"),
                            ("Y1S2", "Year 1 Semester 2"),
                            ("Y2S1", "Year 2 Semester 1"),
                            ("Y2S2", "Year 2 Semester 2"),
                            ("Y3S1", "Year 3 Semester 1"),
                            ("Y3S2", "Year 3 Semester 2"),
                            ("Y4S1", "Year 4 Semester 1"),
                            ("Y4S2", "Year 4 Semester 2"),
                        ],
                        default="Y1S1",
                        max_length=5,
                        verbose_name="Academic Term",
                    ),
                ),
                (
                    "semester_gpa",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="Semester GPA",
                    ),
                ),
            ],
        ),
    ]
